server:
  port: 8086
  servlet:
    contextPath: /finco-api/v1

finco:
  frontend:
    url: http://localhost:4200

spring:
  application:
    name: finco
  datasource:
    url: jdbc:mysql://${DbUrl}/Finco?createDatabaseIfNotExist=true
    username: ${UserDb}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${github-client-id}
            client-secret: ${client-secret}
            scope: 
              - read:user
              - user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: GitHub
            authorization-grant-type: authorization_code
          google:
            client-id: ${google-client-id}
            client-secret: ${google-client-secret}
            scope: 
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google
            authorization-grant-type: authorization_code

# configuration of logging
logging:
  level:
    '[com.finco.finco]': INFO
    '[org.springframework.web]': INFO
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7

springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  swagger-ui:
    operationsSorter: method
