server:
  port: 8086
  servlet:
    contextPath: /finco-api/v1

finco:
  frontend:
    url: ${FRONTEND_URL}

spring:
  application:
    name: finco
  datasource:
    url: jdbc:mysql://${DbUrl}/Finco?createDatabaseIfNotExist=true
    username: ${UserDb}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: 
              - read:user
              - user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: GitHub
            authorization-grant-type: authorization_code
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: 
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google
            authorization-grant-type: authorization_code
  ai:
    openai:
      api-key: ${openai-key}
      chat:
        options:
          model: "gpt-5-nano"
          temperature: 1
          top-p: 1
    mcp:
      server:
        base-url: ${server.servlet.context-path}
        sse-endpoint: /sse
        sse-message-endpoint: /mcp/message
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

# configuration of logging
logging:
  level:
    '[com.finco.finco]': INFO
    '[org.springframework.web]': INFO
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7

springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  swagger-ui:
    operationsSorter: method
